### ISSUE TITLE
Llava support ?

### ISSUE THREAD

**Issue by oddpxl** [utilityai/llama-cpp-rs#113]
Would you consider adding llava support ?

https://github.com/ggerganov/llama.cpp/tree/master/examples/llava

( multimodal support with llama.cpp - llava 1.5 / 1.6  and others ) 

I presume this is out of scope for this project - but had to ask :)

Best,
//O.

**Comment by MarcusDunn** [comment]
What would llava support consist of? Is there any specific API's that are not available?

I'd consider most of the code in https://github.com/ggerganov/llama.cpp/tree/master/examples/llava to be out of scope for us to recreate or wrap. 

If there is something preventing you from recreating those examples in rust due to lack of support in llama-cpp-rs, then I'd likely be open to adding it.

**Comment by oddpxl** [comment]
Makes sense - had to ask :)

I need to dissect the example to see what it would take - not sure my rust is up to scratch ( but I'll give it a go )

At the moment I'm having rust spawn the llava-cli executable - obviously not ideal :)
